### ISSUE TITLE
(WIP) YAML as CSS Pre-processor + Rework as Post-processor

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/blankr#18]
Why not? All mixins and etc will be plugins, lol. if-else'es with some basic template engine? Haha.

[demo with js-yaml](http://nodeca.github.io/js-yaml/#yaml=CmhlbHZldGljYTogJmhlbHZldGljYSAnIkhlbHZldGljYSBOZXVlIiwgSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZicKZ2VvcmdpYTogJmdlb3JnaWEgICAgICdHZW9yZ2lhLCBDYW1icmlhLCAiVGltZXMgTmV3IFJvbWFuIiwgVGltZXMsIHNlcmlmJwpsdWNpZGlhOiAmbHVjaWRpYSAgICAgJyJMdWNpZGEgR3JhbmRlIiwgVGFob21hLCBWZXJkYW5hLCBBcmlhbCwgc2Fucy1zZXJpZicKdmVyZGFuYTogJnZlcmRhbmEgICAgICdWZXJkYW5hLCBHZW5ldmEsIHNhbnMtc2VyaWYnCgojIENvbG9ycyAodmlhIGh0dHA6Ly9jbHJzLmNjIC0gc2xpZ2h0bHkgbW9kZGVkKQpuYXZ5OiAmbmF2eSAgICAgICAnIzAwMUYzRicKYmx1ZTogJmJsdWUgICAgICAgJyMwMDc0RDknCmdyZWVuOiAmZ3JlZW4gICAgICcjMkVDQzQwJwpsaW1lOiAmbGltZSAgICAgICAnIzAxRkY3MCcKeWVsbG93OiAmeWVsbG93ICAgJyNGRkRDMDAnCm9yYW5nZTogJm9yYW5nZSAgICcjRkY4NTFCJwoKZm9udC1jb2xvcjogJmZvbnQtY29sb3IgI2FuZCBgKm9yYW5nZWAgCgpib3JkZXJlZDogJmJvcmRlcmVkCiAgYm9yZGVyLXJhZGl1czogNXB4CiAgYm9yZGVyOiAqb3JhbmdlICNzaG91bGQgYmUgYCpmb250LWNvbG9yYAogIGZvbnQtZmFtaWx5OiAqdmVyZGFuYQogIGNvbG9yOiAqYmx1ZQoKLmZvbzoKICA8PDogKmJvcmRlcmVkCgouYmFyOgogIDw8OiAqYm9yZGVyZWQKICBjb2xvcjogbGltZQogIGJvcmRlci1yYWRpdXM6IDEwcHgKCi5iYXo6CiAgPDw6ICpib3JkZXJlZAogIGZvbnQtZmFtaWx5OiAqaGVsdmV0aWNhCiAgYmFja2dyb3VuZC1zaXplOiAxNTVweAoK)
**index.js**

``` js
var readYaml = require('read-yaml');
var map = require('object.map');

readYaml('roots.settings.yaml', function(err, data) {
  if (err) throw err;
  var orig = data.vars;
  data.vars = map(data.vars, function(val, key, obj) {
    return obj.hasOwnProperty(val) ? obj[key] = obj[val] : obj[key];
  });

  console.log(data)
});
```

**roots.settings.yml**

``` yaml
# ---------------
# Global Settings
# ---------------
vars:
  # Font stacks (add your own!)
  helvetica-neue:   '"Helvetica Neue", HelveticaNeue, Helvetica, Arial, sans-serif'
  helvetica:        '"Helvetica Neue", Helvetica, Arial, sans-serif'
  georgia:          'Georgia, Cambria, "Times New Roman", Times, serif'
  lucidia-grande:   '"Lucida Grande", Tahoma, Verdana, Arial, sans-serif'
  verdana:          'Verdana, Geneva, sans-serif'

  # Default font settings
  font-stack:  verdana
  font-size:   16
  font-color:  green

  # Colors (via http://clrs.cc - slightly modded)
  navy:      '#001F3F'
  blue:      '#0074D9'
  aqua:      '#7FDBFF'
  teal:      '#39CCCC'
  olive:     '#3D9970'
  green:     '#2ECC40'
  lime:      '#01FF70'
  yellow:    '#FFDC00'
  orange:    '#FF851B'
  red:       '#D13F19'
  maroon:    '#85144B'
  fuchsia:   '#F012BE'
  purple:    '#B10DC9'
  white:     '#FFFFFF'
  silver:    '#DDDDDD'
  gray:      '#AAAAAA'
  black:     '#222222'

  # Default color
  default-color: blue

  # Text highlight color
  highlight-color: teal

  # Custom image base path for roots mixins
  img-path: ''

  # Support for old IE
  support-for-ie: false

  # Ligatures
  ligatures: false

  # Vertical rhythm
  base-line-height: font-size
  default-rhythm-border-style: solid
  relative-font-sizing: true
  round-to-nearest-half-line: false
  min-line-padding: 2px
```
